name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
  packages: write
  pull-requests: read
jobs:
  proto-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run buf checks
        uses: bufbuild/buf-action@v1
        with:
          format: true
          lint: true
          breaking: true
  lint:
    runs-on: ubuntu-latest
    needs: [proto-check]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Run linting
        uses: golangci/golangci-lint-action@v8
        with:
          only-new-issues: true
  test:
    runs-on: ubuntu-latest
    needs: [proto-check, lint]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Test
        run: go test -v ./...
  container-build:
    runs-on: ubuntu-latest
    needs: [proto-check, lint, test]
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Set up ko
        uses: ko-build/setup-ko@v0.9
      - name: Build and push
        run: ko build --bare --platform linux/amd64,linux/arm64 -t "${{ github.sha }}" -t "latest" ./cmd/weather-lady
