name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  proto-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run buf checks
        uses: bufbuild/buf-action@v1
        with:
          format: true
          lint: true
          breaking: true
  check:
    runs-on: ubuntu-latest
    needs: [proto-check]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
      - name: Check formatting
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "The following files are not formatted:"
            gofmt -s -l .
            exit 1
          fi
      - name: Run linting
        uses: golangci/golangci-lint-action@v6
  test:
    runs-on: ubuntu-latest
    needs: [proto-check, check]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
      - name: Test
        run: go test -v ./...
  container-build:
    runs-on: ubuntu-latest
    needs: [proto-check, check, test]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v5
        with:
          file: Containerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
